### ISSUE TITLE
Support for fetchmail.pl

### ISSUE THREAD

**Issue by tsvsj** [technicalguru/docker-mailserver-postfixadmin#13]
From my understanding fetchmail via `fetchmail.pl` is currently not supported, because there is no cron installed in the image. This is a required feature for me and therefore, I would be really happy, if you could just add the cron package and a corresponding job to execute `/var/www/html/ADDITIONS/fetchmail.pl` once per minute (or with a configurable interval via `ENV`) into the image. 😃 

Thanks!

**Comment by tsvsj** [comment]
Just for the interested ones: I've found a workaround, which seems to work smoothly as a first attempt:
```
fetchmail:
  image: volkerraschek/postfixadmin-fetchmail:latest
  environment:
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=database.server
    - DATABASE_PORT=3306
    - DATABASE_NAME=mailserver
    - DATABASE_USER=mailserver_db_user
    - DATABASE_PASSWORD=mailserver_db_password
  volumes:
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    - /etc/localtime:/etc/localtime:ro
fetchmail-restarter:
  image: docker
  volumes: 
    - "/var/run/docker.sock:/var/run/docker.sock"
  command:
    - "/bin/sh"
    - "-c"
    - "while true; do sleep 60; docker restart mailserver-fetchmail-1; done"
  restart: unless-stopped
```

The service `fetchmail` executes the `fetchmail.pl` once and then stops. Unfortunately the image doesnt make use of cron. However, the second service, `fetchmail-rester`, uses an instance of docker to request the actual `fetchmail`-server every 60 seconds.

As said, not the most elegant solution, but seems to work as a quick solution. 👍
